### PR TITLE
reactome update - including diseases and drugs

### PR DESCRIPTION
**Pull request by goodb**
Testing for sars-covid model translation.

### CODE REVIEW

**Comment by kltm** [comment]
@goodb It looks like this is still underway? Ping me when finalized and we can try and get it out today.

**Comment by goodb** [comment]
@kltm these models are good to go with that last change.  But will need a fresh REACTO build available at the expected /extensions location before you load it up.

**Comment by kltm** [comment]
Great. I'll wait until we get a good build of it later today, then pull it in, rebuild, etc.

**Comment by ukemi** [comment]
This is fine but I think it would be nice to see these live someplace other than dev. Dev should be the development server we use for testing, don't you think?

**Comment by kltm** [comment]
@ukemi Theoretically, yes, but building up the large number of things that we'd need in place to do stuff like that (e.g. multiple centrally controlled instances that require little overhead) more "properly" has not been resourced since very early on. Part of this is touched on in the "production footing" threads that we talk about.

**Comment by ukemi** [comment]
No worries @kltm. Just being a squeaky wheel, but it sounds like we are on the same page.

**Pull request merged**
