### PR TITLE
SynGO: Switched back to using MOD URI's (when available)

### PR DESCRIPTION
**Pull request by dustine32**

### CODE REVIEW

**Comment by kltm** [comment]
@dustine32 so we want to eyeball these first?

**Comment by kltm** [comment]
@dustine32 where was your branch coming from? I've just updated `master` -> `dev`, could you re-apply?

**Comment by dustine32** [comment]
@kltm Yeah I checked out one of them (SYNGO_2082.ttl) after loading it into my Noctua instance and it looked OK. I can certainly try more of them.

I don't see the typical "CONFLICT" markup in the diffs for these files. Does that come after they're merged? Otherwise, beyond the obvious URI changes and rearrangement of OWL elements, I can't see where the conflicts are.

I'll look at some more in my Noctua and report back. Thanks!

**Comment by dustine32** [comment]
My branch was from here: https://github.com/dustine32/noctua-models/tree/dev

**Comment by dustine32** [comment]
Yep, I'll reapply the model changes. Thanks!

**Comment by kltm** [comment]
I believe you're live now:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:SYNGO_2927

**Comment by dustine32** [comment]
Awesome thanks! I hope @lpalbou likes what he sees

**Pull request merged**
