### PR TITLE
remove non-protein non-complex from enablers of binding reactions

### PR DESCRIPTION
**Pull request by goodb**

### CODE REVIEW

**Comment by goodb** [comment]
@kltm please merge and rebuild when convenient.  Hopefully before Wednesday meeting this week.

**Comment by kltm** [comment]
Could you check to see if the correct reacto.owl is on `snapshot` already? If not, we'll have to at least wait until chebi.owl is available again and finish the currently failed  `snapshot` run.

**Comment by goodb** [comment]
@kltm without time for a more detailed look, the timestamp in the ontology metadata doesn't match with the release version here: https://github.com/geneontology/pathways2GO/releases/download/v0.1.0/REACTO.owl suggesting that this is not correct.  

I can't remember if you are just downloading that or are actually generating it.  If generating it and you started the process after about 11:45am yesterday, then it should be good.

**Comment by goodb** [comment]
@kltm note that I have not been incrementing the release number when I update that ontology and jar file as I think you are pulling it from a hard coded URL in the pipeline.  Let me know if that should change.

**Comment by kltm** [comment]
@goodb The current process, started at midnight (now restarted as chebi is back), will finish later tonight. That said, as you mention in gitter, it doesn't matter we we'll go ahead.

**Pull request merged**
