### PR TITLE
pretty please.. just add full view of TCF Wnt for Paul Thomas

### PR DESCRIPTION
**Pull request by goodb**
Needs the one with this title "TCF-dependent_signaling_in_response_to_Wnt.ttl"

### CODE REVIEW

**Comment by kltm** [comment]
Above, "Files changed" is listed as "∞" and I can't see a diff. Do you know what's up with that?

**Comment by goodb** [comment]
Probably related to addition and removal of thousands of files in past few commits.  This pr should only have one new file from me since the last reactome import.  If the git  history is the problem I can try blowing mine away, starting over from what’s in dev and adding the file in question.

**Comment by kltm** [comment]
@goodb Yeah, that first commit seems to throw a lot off. Would you mind rebasing or just starting a new PR?

**Comment by kltm** [comment]
(or resetting)

**Comment by goodb** [comment]
Okay new pr in.  Looks  like it ought to go smoother.

**Pull request closed without merging**
