### PR TITLE
First test set of syngo annotation ttl files

### PR DESCRIPTION
**Pull request by dosumis**
First test-set of syngo annotation ttl files.  These are simply for load testing are not intended as final models for release.

### CODE REVIEW

**Comment by kltm** [comment]
Notes from first local check of these files. Tagging @cmungall and @balhoff 

### Looking at minerva metadata call

When getting metadata, minerva returns:
```
2017-05-09 15:42:56,037 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_113.owl
2017-05-09 15:42:56,042 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_92.owl
2017-05-09 15:42:56,043 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_203.owl
2017-05-09 15:42:56,044 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_80.owl
2017-05-09 15:42:56,046 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_50.owl
2017-05-09 15:42:56,047 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_38.owl
2017-05-09 15:42:56,049 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_138.owl
2017-05-09 15:42:56,052 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_164.owl
2017-05-09 15:42:56,052 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_132.owl
2017-05-09 15:42:56,055 ERROR (OperationsImpl:622) No annotations found for model: http://model.geneontology.org/SYNGO_110.owl
```

The model metadata for these returns no contributors, state, or date (a lot these are obviously related to the above, but I'll be explicit).

The models IDs apparently have the `.owl` extension, which is misleading, and I suspect would eventually cause issues in routing.

### Examining a model (gomodel:SYNGO_110.owl)

The model contains no title.

### Things I thought might break but didn't

The syngo uuid generation for instances has not had any issues that I have seen yet.
I have not tried the whole lifecycle yet, but it seems to work well with basic editing.

**Comment by cmungall** [comment]
I think OperationsImpl:622 should be LOG.warning not LOG.error?

Seems we need a validator. Should be relatively easy to add to minerva-cli. Ideally we would tweak the minerva code so it actually records warnings/errors rather than logging them, but just having a way to see the logs from cli would be useful

**Comment by dosumis** [comment]
OK . So looks like I just need to add missing metadata on the models and drop the .owl extension in favor of .ttl . Easy enough.  Will Fix ASAP

On #392 Seth wrote:
>  we have not discussed their lifecycle within Noctua.

These are just for testing.  I'd like to delete them once I've had a chance to look over them with they SynGO curators.  We'll only start a pipeline through Noctua once any wrinkles have been ironed out.

**Comment by kltm** [comment]
As far as lifecycle goes, once they are in noctua we have no mechanism for locking, layout, or removal; we would have to stop the system, manually remove them, and do a rebuild, which is unfortunately a bit tedious right now (and the reason I've been testing locally).

**Comment by dosumis** [comment]
Files now have metadata. filename matches URI (both .ttl).  Filenames and titles include _test to indicate that this is not intended for release.  Should be fine to load these into main noctua instance. We already have plenty of LEGO models that are only for testing purposes.

**Comment by kltm** [comment]
Notes taking a look at the models locally:
* user identifiers seem to be string nicknames; these need to be some kind of universal identifier
* dates need to need in the form `2017-05-13`, not `2017.05.13`
* all models need a state; while we are still discussing lifecycle, I would suggest `delete`
* SynGO model identifiers still contain an extension:
 http://localhost:8910/editor/graph/gomodel:SYNGO_138_test.ttl
 vs.
 http://localhost:8910/editor/graph/gomodel:581e072c00000020
 that will cause issues with routing
Possible issues:
* Looking at http://localhost:8910/editor/graph/gomodel:SYNGO_138_test.ttl, some entity identifiers are of the form `obo:UniProtKB_O35509`, which strikes me as off but...
Best practices:
* All models should have human-readable titles and/or contain searchable terms; this is obviously not completely enforced at this point (several open tickets, from title autogeneration to requiring titles during interactive creation), but always nice to have

**Comment by kltm** [comment]
I'll talk to @cmungall about lifecycle issues for models tomorrow.

**Comment by dosumis** [comment]
On May 14, 2017, at 6:13 PM, kltm <notifications@github.com> wrote:
> 
> Notes taking a look at the models locally:
> 
> user identifiers seem to be string nicknames; these need to be some kind of universal identifier
We need some way to deal with this ASAP.  I’m unlikely to be able to get orcids for all - certainly not quickly.   Can we follow the old GO curator tag-value (DB:acc) route  => syngo:gundelfinger, or should I come up with a full IRI?  Have made up IRI scheme for now.  Using as string rather than IRI (following orcid use in noctua OWL models).
> dates need to need in the form 2017-05-13, not 2017.05.13
Fixed.
> all models need a state; while we are still discussing lifecycle, I would suggest delete
> SynGO model identifiers still contain an extension:
> http://localhost:8910/editor/graph/gomodel:SYNGO_138_test.ttl <http://localhost:8910/editor/graph/gomodel:SYNGO_138_test.ttl>
> vs.
> http://localhost:8910/editor/graph/gomodel:581e072c00000020 <http://localhost:8910/editor/graph/gomodel:581e072c00000020>that will cause issues with routing
Fixed (keeping on filenames but not URL as here: https://github.com/geneontology/noctua-models/tree/SynGO-test-files/models <https://github.com/geneontology/noctua-models/tree/SynGO-test-files/models>).  BTW, is this munging of URLs a test server thing?

e.g. 

http://model.geneontology.org/SYNGO_50_test.ttl
>
http://localhost:8910/editor/graph/gomodel:SYNGO_138_test.tt

?
> Possible issues:
> Looking at http://localhost:8910/editor/graph/gomodel:SYNGO_138_test.ttl <http://localhost:8910/editor/graph/gomodel:SYNGO_138_test.ttl>, some entity identifiers are of the form obo:UniProtKB_O35509, which strikes me as off but…
> obo:UniProtKB_O35509
Assume you are using prefix notation here 

> obo:UniProtKB_O35509
>

http://purl.obolibrary.org/obo/UniProtKB_P63011

I was following Chris’ instructions.  But checking recently generated models on noctua I see this pattern:

http://identifiers.org/uniprot/P63011
I have switched.
> Best practices:
> All models should have human-readable titles and/or contain searchable terms; this is obviously not completely enforced at this point (several open tickets, from title autogeneration to requiring titles during interactive creation), but always nice to have
I could ask the SynGO guys to add these, but the ID number is their main method for tracing so should stay in the title.

**Comment by dosumis** [comment]
CC @ftwkoopmans

**Comment by kltm** [comment]
I'm fairly neutral about the rest, although @cmungall should comment here is he sees anything. I would not that for the user IDs though, it would probably be best to have them on a neutral platform; the temporary ones that you've created are probably fine though for now (although they will naturally not be able to edit, change layouts, etc.).

I think the final point would be that all models need to have a state, I would suggest `delete` or `development` for the time being.

**Comment by dosumis** [comment]
All models have status delete.  Command line option on syngo_2_lego allows that to be switched to dev once we are importing stable models.

**Comment by dosumis** [comment]
Is it possible to run this on the main server so that we can view in Noctua for testing?

**Comment by kltm** [comment]
@dosumis Thank you for playing along with us as we work through these.
Most things seems okay enough now, and we will try and get these onto the public server later today.

We did, however, run into some issues with the evidence that would be very good to fix for the next batch.
* evidence individuals should be be shared; an example is gomodel:SYNGO_110_test, where there are two references to each evidence individual; these should be cloned or otherwise not be shared
* all evidence, and pretty much *everything* must include date and contributor (some already do)--everything in the model should be at least traceable with these

**Comment by dosumis** [comment]
> evidence individuals should be be shared; an example is gomodel:SYNGO_110_test, where there are two references to each evidence individual; these should be cloned or otherwise not be shared

I assume the first clause here should say 'not shared'?  I've switched the code to generate new sets of evidence individuals for each edge annotated.  

On this subject: I'm currently only annotating the enabled_by edges, not the 'extensions'.  Perhaps I should be annotating both.  @cmungall @ftwkoopmans - any opinion on this?

> all evidence, and pretty much everything must include date and contributor (some already do)--everything in the model should be at least traceable with these

All evidence should be right now (please let me know if any exceptions).  But you're saying that the individuals should be annotated with PMID and contributor too?

**Comment by kltm** [comment]
"not shared"
Every entity should have the contributor and date. For evidence, I'm actually not sure off the top of my head if the reference (PMID) is "required" or not, but that can be fixed later on. I just want to ensure the minimal information.

**Comment by kltm** [comment]
Sorry, I'm looking at getting these in tomorrow now--we need a little more time to straighten out some issues with the updates at this end.

**Comment by kltm** [comment]
@dosumis In reference to https://github.com/geneontology/noctua-models/pull/28/commits/94bd9c27f1aa5c95936d531c1be51ebac44623f4 , it seems like some models (SYNGO_110_test) are still using shared individuals in evidence.

However, as is doesn't completely bork the interface right now, I'll pull these into master temporarily for examination.

**Comment by dosumis** [comment]
> On May 18, 2017, at 12:59 AM, kltm <notifications@github.com> wrote:
> 
> @dosumis <https://github.com/dosumis> In reference to 94bd9c2 <https://github.com/geneontology/noctua-models/commit/94bd9c27f1aa5c95936d531c1be51ebac44623f4> , it seems like some models (SYNGO_110_test) are still using shared individuals in evidence.
> 
> 

Here are the 2 evidence sets on SYNOGO_110.  They look like distinct individuals to me.






From commit 94bd9c (MD5 (/repos/noctua-models/models/SYNGO_110_test.ttl) = e365f44344cd7324bd1f21ffa1bb5be9)

**Comment by kltm** [comment]
It is indeed working now; I wonder if something got picked up that was missed before with all the recent restarts.

**Pull request merged**
