### PR TITLE
Create replace_relations.tsv

### PR DESCRIPTION
**Pull request by vanaukenk**
Adding the tsv for replacing relations

### CODE REVIEW

**Comment by kltm** [comment]
@vanaukenk Should the first row not be a comment? (That would simplify the format and parsing down the road.)

**Comment by kltm** [comment]
For https://github.com/geneontology/minerva/issues/465
Originating at https://github.com/geneontology/minerva/pull/477#issuecomment-1110973103

**Comment by vanaukenk** [comment]
@kltm - can we still get a nice table view if the first row is a comment?

**Comment by kltm** [comment]
@vanaukenk The display should be separate from the data. Or is this a case where you're trying to game GitHub to give you a nice interface? If the latter, I think we should go with the format that makes the most sense in a frontend generic way and consider handling editing as a secondary concern.

**Comment by kltm** [comment]
(I am also trying to find an answer to your question and/or a workaround.)

**Comment by kltm** [comment]
https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files#rendering-csv-and-tsv-data

**Comment by kltm** [comment]
@vanaukenk It still makes a table, with the first row's first entry containing a hash tag.

**Comment by kltm** [comment]
Now, that said, I am suddenly unsure if TSV is generally considered to contain its own metadata in the first line, or if that is just a convention some people use...

**Comment by kltm** [comment]
Apologies, I've come full circle and withdraw and complaint.

**Review by kltm — APPROVED** [review]
I'm not sure why that first line weirds me out, but it is apparently a pretty common convention.

**Pull request merged**
