### PR TITLE
Reactome release 82 models from geneontology/reactome-go-cams#9

### PR DESCRIPTION
**Pull request by dustine32**
Drop-N-Reload of Reactome models in Noctua production using Reactome release 82 data. Models are from https://github.com/geneontology/reactome-go-cams/pull/9. @ukemi and @deustp01 have tested these in noctua-dev as noted in https://github.com/geneontology/pathways2GO/issues/176#issuecomment-1294939557.

Hopefully this can be pulled in during the [2022-11-10 Noctua outage](https://github.com/geneontology/noctua/issues/798)?

### CODE REVIEW

**Comment by dustine32** [comment]
Noting an [issue spotted](https://github.com/geneontology/noctua/issues/798#issuecomment-1307729958) by @ukemi but it doesn't block this PR from going in. The group search does not work for these models and I figured out that it's due to "https" in each model's `providedBy` vs "http" in [groups.yaml](https://github.com/geneontology/go-site/blob/8cc9d3585a7b5c15bbbd9d69915a639c916dcc2e/metadata/groups.yaml#L201):
image
image
@deustp01 @ukemi Which do you prefer, "http" or "https"?
We'll make a ticket in the appropriate repo (depends on the answer) and plan to get this in on the next load.

**Comment by ukemi** [comment]
When I navigate to Reactome it is https. I guess that would be the correct one. You probably know better than I.  :)

**Comment by kltm** [comment]
If this data has not leaked elsewhere (remember that these are _identifiers_, not URLs), it would be good to get them onto the one with a more likely future: https.

**Comment by deustp01** [comment]
https should be right.

**Review by kltm — APPROVED** [review]
Gunna go with whatever @dustine32 sez here

**Pull request merged**
