### PR TITLE
Zfin import models

### PR DESCRIPTION
**Pull request by sierra-moxon**
round 2 attempt for a clean PR into master of all ZFIN models, without spurious deletes that we saw in: https://github.com/geneontology/noctua-models/pull/182
The large number of commits is just a result of the number of files being too long to add in a single commit. 
Travis is failing because the logging output is too long - should we just move to github actions?

### CODE REVIEW

**Comment by dustine32** [comment]
@sierra-moxon The models I spot-checked look good! Unfortunately there's a [bug](https://github.com/geneontology/gocamgen/issues/89) we discovered in the ART workshop today that affects Noctua Form and ShEx. I'm testing a fix for this right now. Once it's merged into ontobio the models would need to be regenerated. Sorry!

**Comment by dustine32** [comment]
@sierra-moxon OK, that bug's been [fixed](https://github.com/biolink/ontobio/pull/552) in ontobio so, if you git pull from `master` and regen, you should be good. Unfortunately, you'd also have to reset the `modelstate` to "production" again. Grr, need to add that option to the gocamgen code.

**Comment by sierra-moxon** [comment]
@dustine32  - I regenerated the ZFIN models after updating to the latest version of ontobio to pull in the fix.  I updated this branch accordingly so you should be able to see the differences here?  Could you tell me what I'm looking for to see if it all worked properly with the fix?  thanks a bunch! :). I also put in a PR for dev so that we could see it on noctua-dev (and I'm running the shex locally as well).

**Comment by dustine32** [comment]
@sierra-moxon Oh, that fix should've added `providedBy` properties to all `NamedIndividual`s, like:
```
<http://model.geneontology.org/ZFIN_ZDB-GENE-000125-12/5d91e57a-b95d-4482-a269-1d15fd486dd9> a GO:0008285,
        owl:NamedIndividual ;
    dc:contributor "GOC:zfin_curators" ;
    dc:date "2004-09-17" ;
    ns2:providedBy "http://zfin.org" .
```
But I just see:
```
<http://model.geneontology.org/ZFIN_ZDB-GENE-000125-12/5d91e57a-b95d-4482-a269-1d15fd486dd9> a GO:0008285,
        owl:NamedIndividual ;
    dc:contributor "GOC:zfin_curators" ;
    dc:date "2004-09-17" .
```
Either code didn't update or there's another bug preventing this. I can eventually try the ZFIN GPAD myself.

**Comment by sierra-moxon** [comment]
@dustine32 - ok, another attempt - these should have 'production' status, and providedBy tag.  (see accompanying dev PR: https://github.com/geneontology/noctua-models/pull/187) :) Would you mind taking a quick look? (not ready to merge until rest of testing has been done).

**Review by dustine32 — APPROVED** [review]
Looks good. Loaded a few into my Noctua instance checking for state = "production," `providedBy` on all individuals and edges, etc.

**Comment by kltm** [comment]
Here we go!

**Pull request merged**
