### PR TITLE
adding ZFIN models

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Comment by sierra-moxon** [comment]
@kltm - I'm not sure what those conflicts were about - lets try a new PR. :)

**Comment by kltm** [comment]
Okay, passes about as much anything these days due to geneontology/noctua-models#144

**Comment by kltm** [comment]
@sierra-moxon 
Is there a ticket for the import process on the GO side somewhere?
It looks like on the next iteration, the ZFIN group, species, and a different contributor might be good additions--they are a little hard to find right now.

**Comment by sierra-moxon** [comment]
> @sierra-moxon
> Is there a ticket for the import process on the GO side somewhere?
> It looks like on the next iteration, the ZFIN group, species, and a different contributor might be good additions--they are a little hard to find right now.

I put this one in this morning: https://github.com/geneontology/noctua-models/issues/170 -- right repo? @kltm

**Pull request merged**
