### PR TITLE
Updated SynGO models from geneontology/syngo-go-cams#2

### PR DESCRIPTION
**Pull request by dustine32**
Intended for merge into `master` whenever @vanaukenk or other testers approve this is OK to go.

This will have effects in the GO pipeline related to https://github.com/geneontology/go-site/issues/1847:
1. ECO codes updated in https://github.com/geneontology/syngo2lego_data_conversion/issues/5 will allow these (previously failing) annotations to pass QC and so will increase annotation count.
2. Increase in SynGO models since last update, 2196->3241 will also increase annotation count substantially. Mostly in mouse but likely also in other SynGO-annotated organisms.

### CODE REVIEW

**Comment by vanaukenk** [comment]
@thomaspd - please let me know if you plan to look over these models on noctua-dev with Frank before they go onto noctua-production.  Thanks.

@dustine32 @kltm

**Comment by dustine32** [comment]
Added missing model SYNGO:1805. Details in https://github.com/geneontology/syngo-go-cams/pull/4.

**Comment by dustine32** [comment]
Frank approves! From 2022-06-30 email:
> I've reviewd a dozen random models on the noctua-dev site you linked, looks fine to me !

**Comment by kltm** [comment]
Great--this has already been added to the list for July: https://github.com/geneontology/noctua/issues/782

**Comment by kltm** [comment]
Yes, reapplication would make the most sense.
This will keep happening as we do a reordering to make the diffs easier.
In the future, if this was just an "add on" repo, we could avoid that.

**Review by kltm — APPROVED** [review]
Assuming we're good if we can merge.

**Pull request merged**
