### PR TITLE
New load of SynGO models from 2023-12-01 JSON

### PR DESCRIPTION
**Pull request by dustine32**
Drop and reload of all SynGO models from new source file. More details in https://github.com/geneontology/syngo-go-cams/pull/6.

We can check how these look in noctua-dev and then load into Noctua prod.

Tagging @kltm @pgaudet since the eventual Noctua prod load would wipe out any manual changes to the SynGO models made since the last [update](https://github.com/geneontology/noctua-models/pull/244) on 2022-10-13. @ftwkoopmans indicates that annotation is made through the [source JSON](https://github.com/geneontology/syngo2lego_data_conversion/blob/master/json/SynGO_export_2023-12-01.json) with the intention that this is loaded into Noctua and then exported as standard annotations into the GO release. From Frank:
> Please let me know when the upstreaming of the data/json we uploaded was successful and in which GO release (approximate date) this data will be integrated.

Happy to discuss further before making/merging any PR to `noctua-models/master`.

### CODE REVIEW

**Comment by kltm** [comment]
@dustine32 SOP is that SynGO is a "locked" upstream and any accidental changes would be removed. If there have been changes to this, that would be important.

**Comment by kltm** [comment]
@dustine32 As long as the volume of models doesn't change, I see no reason not to have them in at the next Noctua outage.

**Comment by dustine32** [comment]
@kltm Great, thanks! There is an increase of 976 models.

**Comment by kltm** [comment]
Go ahead and add to the items at https://github.com/geneontology/noctua/issues/866; also tagging @vanaukenk to give warning for the bump in numbers

**Comment by dustine32** [comment]
Thanks again, @kltm! I'll merge this and check on slack about cycling Noctua dev.

**Pull request merged**
