### PR TITLE
Update replace_relations.tsv

### PR DESCRIPTION
**Pull request by vanaukenk**
Adding changes to 'directly activates' and 'directly inhibits' with tabs and newline

### CODE REVIEW

**Comment by kltm** [comment]
@vanaukenk I'm noticing that there seems to be no label for the final column?

**Comment by vanaukenk** [comment]
Okay, phew.  That's what I see, too.

**Review by kltm — APPROVED** [review]
Standard update.

**Comment by kltm** [comment]
@vanaukenk So, we can't really merge this until our next outage (without manual intervention). If we do, we will block automated pushes of new models until the remote repo is caught up.
For that reason alone, it may be worth reconsidering keeping all of the update data here. Annoying (and slightly messy), but we could also create a new repo like `noctua-model-migrations` for data like this.

**Comment by vanaukenk** [comment]
Okay, I will not merge this PR today.
I'm agnostic about another repo.  If you think it would be best to have a new repo, I defer to you on that one.
Let me know if I'm not understanding the issue.

**Comment by kltm** [comment]
In discussion with @vanaukenk , we've decided to move the update/replace metadata into a new repo: https://github.com/geneontology/noctua-models-migrations

**Comment by kltm** [comment]
Moved to https://github.com/geneontology/noctua-models-migrations/blob/main/replace_relations.tsv

**Pull request closed without merging**
