### PR TITLE
First production set from SynGO

### PR DESCRIPTION
**Pull request by dosumis**
CC @ftwkoopmans 

@huaiyumi - do you know where to get the GPAD exports from these models to use in PAINT.  Seth should be able to help if not.  Would also be good to make sure that @tonysawfordebi can pick them up for QuickGO.

### CODE REVIEW

**Comment by cmungall** [comment]
@kltm - are we ok to merge this?

**Comment by kltm** [comment]
It should not be merged until there is time to shut down noctua and rebuild (announce, etc.).
If it is merged before that, the github push starts to fail.

**Comment by huaiyumi** [comment]
Is it OK to release them in GO? If so, the PAINT tool can pick them up and we can do PAINT on them. That is probably the most straightforward way to handle it.

**Comment by kltm** [comment]
There may be issues with this model batch, please see: #55

**Pull request merged**
