### PR TITLE
Update to Reactome conversion

### PR DESCRIPTION
**Pull request by goodb**

### CODE REVIEW

**Comment by kltm** [comment]
@goodb You should delete the .DS_Store files from the branch--they are causing issues.

**Comment by kltm** [comment]
@goodb I think I've purged these on `dev`; it looks like you added them to gitignore, but they were already added to the repo.

**Comment by kltm** [comment]
@goodb This should hopefully be live now.

**Comment by goodb** [comment]
Looks like it worked, thanks.  Will add more metadata and make sure to zap the ds_store on next pr.  Apple being helpful..

**Pull request merged**
