### PR TITLE
Updated and new SynGO models for issue #55

### PR DESCRIPTION
**Pull request by dustine32**
@kltm Hopefully I did this PR correctly. Let me know if it's totally wrong: I switched to master on my fork, then copied over updated/new SYNGO models and committed. There are maybe ways to merge specific commits from dev to master?

### CODE REVIEW

**Comment by kltm** [comment]
This looks right to me, but I don't think I'll cycle until early next week.
There are things that can cherrypick, but git is tree-based in nature, so I tend to try not fight it.

**Comment by dustine32** [comment]
Ok, awesome! Time-wise I'm in no hurry as I just reopened the model title debate. We'll see what they say. Thanks again!

**Comment by kltm** [comment]
@dustine32 Just to clarify here (and from discussion on some other thread somewhere), I'm paused on merging waiting on clarification, and hopefully addition, of SynGO titles.

**Comment by kltm** [comment]
Honestly, as these are the bulk of our production models and the current SynGO models are kinda borked, I'd be in favor of just getting these out. But yes, it's not a bad idea to run them through noctua-dev first.

**Comment by dustine32** [comment]
OK @kltm . Shouldn't hurt then to create this PR to dev #82 .

**Pull request merged**
