### PR TITLE
SynGO2LEGO models regenerated through @dosumis' code; issue #55

### PR DESCRIPTION
**Pull request by dustine32**
Just ran file SynGO_export_test.json for examples.

### CODE REVIEW

**Comment by kltm** [comment]
Clarifying that only nine models changed?

**Comment by dustine32** [comment]
@kltm Yep, only nine. I only ran it on a few annotations for examples.

If you'd like, I can run the full JSON source file containing 2179 models and submit a new PR? Thanks!

**Comment by thomaspd** [comment]
Yes, I think we should try on all the SynGO models, now that they are using ORCIDs.  @kltm is there anything else we need to resolve first?

**Comment by kltm** [comment]
@dustine32 @thomaspd 
I'm happy to take any number onto `dev`, but all of them would naturally make looking for additional issues easier.

**Comment by dustine32** [comment]
@kltm @thomaspd Cool, I'll get all of the models converted then. So the first issue that popped up when running the whole list was an out-of-date ontology file "go-simple.ofn". This file's from late Aug 2017 and the new annotations use terms added after that. Ex. GO:0099170

@dosumis Do you know where I can get an updated ofn file?

In the meantime I'll try to fish out other issues in the model list.

**Comment by dosumis** [comment]
> @kltm @thomaspd Cool, I'll get all of the models converted then. So the first issue that popped up when running the whole list was an out-of-date ontology file "go-simple.ofn". This file's from late Aug 2017 and the new annotations use terms added after that. Ex. GO:0099170

> @dosumis Do you know where I can get an updated ofn file?

Just grab the latest GO file.  http://purl.obolibrary.org/obo/go.owl should be fine.

**Comment by dustine32** [comment]
Awesome @dosumis thanks! Now it looks like it made it through most models before one to an obsolete term erred it out again.

I can probably skip SynGO annotations to obsolete terms, right @thomaspd ? Specifically, UniProtKB:P70569 annotated GO:0099090 (model SYNGO:1805).

**Pull request merged**
