### PR TITLE
Full regen of MGI, WB OA import models - Fixed model titles (add symbols)

### PR DESCRIPTION
**Pull request by dustine32**
This PR fixes the model titles according to https://github.com/geneontology/gocamgen/issues/90.

I'm just going to copy over my beautiful writeup from [yesterday's PR](https://github.com/geneontology/noctua-models/pull/192):

--------------------------------------------------------

Drop and reload of 13480 MGI models.
Drop and reload of 155 WB models from `wb_oa_3.gpad`. Also removed the 3480 older non-`wb_oa_3.gpad`-sourced models since we're not actively generating/testing these right now. @vanaukenk can confirm that this is OK. Otherwise we can add them back.

This load addressed these issues:
- Sets `modelstate` to "production" - geneontology/gocamgen#91 and geneontology/gocamgen#93
- Only single literature reference used per annotation - geneontology/gocamgen#31
- Add with/from back to has_input models when the term is a binding term - biolink/ontobio#566

No errors during gocamgen translation for either MGI or WB.

`go_cam_mgi.gpad` header:
```
!gpa-version: 2.0
!generated-by: MGI
!date-generated: 2021-06-05
```
`wb_oa_3.gpad` header:
```
!gpa-version: 2.0
!generated-by: WormBase
!date-generated: 2021-05-13
```
Also tagging @ukemi

### CODE REVIEW

**Comment by kltm** [comment]
Yesterday's was good, so assuming improvement.

**Comment by ukemi** [comment]
Thanks @kltm and @dustine32 

@LiNiMGI and I will give these a quick review. I don't anticipate any problems. Then we would like it if we could turn the crank once more to get the Noctua GPAD from the new load. I anticipate our schedule will be to spend next Monday and Tuesday. The rest of the week we will start GPAD review. Can you confirm that the right place to open GPAD tickets is in the Minerva tracker?

**Comment by dustine32** [comment]
@ukemi Yeah, https://github.com/geneontology/minerva is probably the best, first place to report something about the GPAD export (knowing that the ticket(s) could eventually get bumped to another repo if the cause is elsewhere/upstream). Thanks for asking!

**Comment by ukemi** [comment]
And of course I'm going to ask, can you throw the GPAD in the Checking Dustin's imports mid-June 2021 folder?

**Comment by dustine32** [comment]
@ukemi No prob! It's there now.

**Comment by vanaukenk** [comment]
Thanks @dustine32 

I've started checking the WB models and so far, the translated annotations look fine.  I'd be happy to start looking at a GPAD output for WB next week, too, if it's possible to generate that file.

There are only two things I've found so far:

1) For the orcids, our input file used https rather than the http that is in the users.yaml file.  Consequently, the curator names don't show up in the Noctua landing page, just the https URL.  Given that we have models on production Noctua with the http orcids, I'm assuming that the best thing to do at this point would be for us to re-generate an import file using http in the contributor URL.  If I update the users.yaml to use https, then we'd lose the curator name on production Noctua, right?  @kltm

2) The gene names on the landing page are displaying correctly, but in the Noctua form and graph the gene ids for uncloned loci do not resolve to a name.  I'm assuming this is because noctua-dev is not accessing the most up-to-date WB gpi file.  If so, this is not a blocker, but it'd be good to know for sure that this is the reason.

Otherwise, things look good!

Note: we didn't populate creation-date and modification-date for this file, but could do that for the next round.

**Comment by kltm** [comment]
@ukemi Unfortunately, as for as URIs go, HTTP and HTTPS are different, so they much match. You can either shift it at your end or we do an upgrade at our end.

**Comment by kltm** [comment]
@vanaukenk  Unfortunately, as for as URIs go, HTTP and HTTPS are different, so they much match. You can either shift it at your end or we do an upgrade at our end.

**Comment by ukemi** [comment]
@dustine32 it looks like there are models missing. I can't find MGI:MGI:1096337.

**Comment by ukemi** [comment]
False alarm. My bad. I refreshed the tool and the model is there. I am certain that I had cleared my existing filters.

**Comment by dustine32** [comment]
@ukemi Phew!

@vanaukenk Sorry, I meant to check for this earlier. Can you send me an example ID of uncloned loci that do not resolve to a name in the form or graph editor?

**Comment by ukemi** [comment]
We should make a decision about the ORCIDs on today's call. We ran into this issue as well. @hdrabkin has standardized the yaml to  http, but we could put in a ticket on our end and change the output.

**Comment by ukemi** [comment]
@dustine32 did you allow for RO:0002491 yet? We are not seeing it in the models. For example Line 7155 on our GPAD spreadsheet shows the annotation with no annotation extensions in the model, MGI_MGI_107168 .

**Comment by vanaukenk** [comment]
The question about ORCIDs is on the agenda for today's call.

**Comment by vanaukenk** [comment]
> @dustine32 did you allow for RO:0002491 yet? We are not seeing it in the models. For example Line 7155 on our GPAD spreadsheet shows the annotation with no annotation extensions in the model, MGI_MGI_107168 .

Shall we make a separate ticket on the minerva tracker for this?  I'm a little concerned we're overloading this PR.

**Comment by dustine32** [comment]
@vanaukenk @ukemi We have https://github.com/biolink/ontobio/issues/572 to update this relation in `ontobio`. This fix was merged into the code and should have allowed this extension to be translated in the models now on noctua-dev. I'll need to figure out what's going on.

**Comment by ukemi** [comment]
Awesome @dustine32. Once you have investigated, can you open the ticket in the appropriate tracker?

**Pull request merged**
