### PR TITLE
Updated SynGO models from geneontology/syngo-go-cams#1

### PR DESCRIPTION
**Pull request by dustine32**
Latest data. All of the details are in PR geneontology/syngo-go-cams#1.

### CODE REVIEW

**Comment by dustine32** [comment]
@kltm These were going to be all ready to go until I just now realized these models don't have their `in_taxon` annotations. I'll try to figure out a fast way to add those and then push a new model set to this branch.

**Comment by kltm** [comment]
No worries. Since we're not setup to go out the door with this today, there is plenty of time to work it through.

**Comment by dustine32** [comment]
OK, this _shooould_ be good for testing in dev now.

**Comment by dustine32** [comment]
Noting that [9198ff7](https://github.com/geneontology/noctua-models/pull/231/commits/9198ff7b85b2a5dfe995526c71d58f77d1cba16b) is sourced from https://github.com/geneontology/syngo-go-cams/pull/2

**Comment by kltm** [comment]
Testing syngo update to dev

**Pull request merged**
