### PR TITLE
Now with evidence on GP to anonymous MF edges.

### PR DESCRIPTION
**Pull request by dosumis**

### CODE REVIEW

**Comment by kltm** [comment]
@dosumis I had thought that yesterday's was the final for a bit.  I'll be on and off for a couple of weeks from Friday, so if there is anything that you'd like in before mid-September, we should coordinate.

**Comment by kltm** [comment]
@dosumis Are you unable to provide ORCIDs for your users? I believe that's what we want to go with for the GO annotations; I also recall we had this discussion before, but I can't find it.
As well, weren't the titles a bit more informative in a previous iteration?

**Comment by dosumis** [comment]
> I had thought that yesterday's was the final for a bit. I'll be on and off for a couple of weeks from Friday, so if there is anything that you'd like in before mid-September, we should coordinate.

Kind of inevitable that I'd notice more issues once we loaded.  It would be good to get the latest batch loaded soon as we'd like to test GPAD conversion.  I was too conservative with which edges I put evidence on for conversion to work reliably with the current load.  We will likely want at least one more batch loaded before the annual SynGO project meeting on the 23rd September, but these will not be ready this week so this can be done when you get back.

> @dosumis Are you unable to provide ORCIDs for your users? I believe that's what we want to go with for the GO annotations; I also recall we had this discussion before, but I can't find it.

Not yet.  The various expert contributors need to be asked for ORCIDs and these need to end up in the SynGO JSON.  We've asked the SynGO guys to request ORCIDs from their experts, but don't know how much progress  has been made. @ftwkoopmans should be able to fill us in on progress.  For now, we've agreed to use 'SynGO:<username>' for the contributors field.  This is no different from GO-CAM models that just have GOC:<initials> for contributor (don't know how common this is now, but I've certainly seen some).

> As well, weren't the titles a bit more informative in a previous iteration?

I think the only difference is that they no longer have 'test' in the title.  Longer, descriptive titles with 'syngo' in come from Barbara's work.

**Comment by kltm** [comment]
Fair enough. I'll try and get this batch up tonight (which, looking at the `mod` flag on the Noctua landing page, may revert some unsaved changes from @BarbaraCzub and @LiNiMGI ).
I'll be unavailable for the next week, then available sporadically the week after that.

**Comment by ftwkoopmans** [comment]
The ORCHIDs are coming, for each annotation we will provide the ORCHID of each contributing annotator, please bear with us as we sort this out throughout the consortium.

**Comment by kltm** [comment]
@ftwkoopmans No problem at all. I'm going to put out what is currently in this PR tonight and can do another one when I am back online in a week or so.

**Comment by kltm** [comment]
@dosumis Merged and now in production.

**Comment by kltm** [comment]
@cmungall As an aside, it takes about 10m to rebuild the journal. I'm pretty happy about that for now.

**Pull request merged**
