### PR TITLE
WB import models to prod from wb_oa_4.gpad

### PR DESCRIPTION
**Pull request by dustine32**
Awaiting @vanaukenk's approval before merging this branch.

Load of WB OA models, same TTL files as in https://github.com/geneontology/wb-go-cams/pull/1, applied to `master` for push to Noctua production.

### CODE REVIEW

**Comment by kltm** [comment]
Clarifying: "big red button" as in a final import?

**Comment by dustine32** [comment]
@kltm Correct!

Though we'll still have the remaining (much, much larger) set of WB annotations from Protein2GO to import later.

**Comment by vanaukenk** [comment]
Thanks @dustine32 @kltm  
I'll double-check a few things today, and let you know when we're good to go.

**Review by kltm — APPROVED** [review]
No problem from my end.
I seem unable to remember the facts around this, but if we take this, I believe there is no other metadata manipulation we need to take at our end, correct?

**Comment by vanaukenk** [comment]
Just noting that we agreed to put the models from the wb_oa_4.gpad file into production during the 2021-12-09 Noctua maintenance outage.

**Pull request merged**
